# Generated by Django 4.0.3 on 2022-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='full name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Contact_No', models.CharField(max_length=17, unique=True, verbose_name='Contact')),
                ('profile_pic', models.ImageField(upload_to='media/profiles')),
            ],
        ),
    ]
